[package]
authors = ["efyang <edward.yang6771@gmail.com>"]
name = "xiami-api"
version = "0.1.0"

[dependencies]
interpolate_idents = "0.1.3"
quick-error = "1.1.0"

[dependencies.top-sdk]
git = "https://github.com/efyang/top-sdk-rs"
